theme: jekyll-theme-cayman
plugins:
 - github-pages
header_pages:
  - privacy_policy.md

title: Trident Cockpit
color: "#20A1BD"
description:  Trident Cockpit is an alternative iPhone/iPad control app for the <a href="https://www.sofarocean.com/products/trident?aff=30">Sofar Trident Underwater Drone.</a>
appstore: https://apps.apple.com/app/id1501545121
google_analytics: UA-158634251-2
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - privacy_policy.md
  - macOS.md
